global:
  scrape_interval:     60s
  evaluation_interval: 5s

scrape_configs:

- job_name: "prometheus-server"
  static_configs:
  - targets:
    - "localhost:9090"

- job_name: "opencensus-agent"
  static_configs:
  - targets: 
    - "opencensus-agent:9100"

- job_name: "trillian-log-server"
  static_configs:
  - targets:
    - "trillian-log-server:8080"

- job_name: "trillian-log-signer"
  static_configs:
  - targets:
    - "trillian-log-signer:8080"

- job_name: "jaeger"
  static_configs:
  - targets:
    - "jaeger:14269"
