# Dependencies:
# Assumes db 'test' database is created see README.md
#
# Environment variables must be exported:
# LOGID -- Trillian Log ID must be created beforehand

version: "3"

services:

  prometheus:
    image: prom/prometheus:v2.10.0
    volumes:
    - "${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml"
    expose:
    - "9090" # Default HTTP Endpoint
    ports:
    - 9090:9090
    healthcheck:
      test:
      - CMD
      - curl
      - --fail
      - "http://prometheus:9090/-/healthy"

  # Assumes "test" database has been initialized outside (!) of Docker Compose (mysql-data)
  db:
    image: mariadb:10.4.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: zaphod
    volumes:
    - "trillian-data:/var/lib/mysql"
    expose:
    - "3306"

  # For Debugging
  adminer:
    depends_on:
    - db
    image: adminer:4.7.1
    ports:
    - 7777:8080

  basic-personality-server:
    depends_on:
    - trillian-log-server
    image: us.gcr.io/${PROJECT}/basic-personality-server@sha256:25774ac8a252e79f8e7fbe8463a887afb408ed054a56d1595dd9d8dfd7ab5e05
    build:
      context: .
      dockerfile: ./Dockerfile.server
    command:
    - --grpc_endpoint=:50051
    - --http_endpoint=:8080
    - --zpgz_endpoint=:9999
    - --tlog_endpoint=trillian-log-server:50051
    - --tlog_id=${LOGID}
    expose:
    - "50051" # gRPC
    - "8080"  # HTTP
    - "9999"  # zPages
    ports:
    - 8080:8080
    - 9900:9900
    - 9998:9999

  basic-personality-client:
    depends_on:
    - basic-personality-server
    image: us.gcr.io/${PROJECT}/basic-personality-client@sha256:67986a541ef3e5e671e9970445311aeb1215c7fc8a97ed777c580c67bee885f3
    build:
      context: .
      dockerfile: ./Dockerfile.client
    command:
    - --grpc_endpoint=basic-personality-server:50051
    - --zpgz_endpoint=:9999
    expose:
    - "9999" # zPages
    ports:
    - 9997:9999

  trillian-log-server:
    depends_on:
    - db
    # See https://console.cloud.google.com/gcr/images/trillian-opensource-ci/GLOBAL        
    image: gcr.io/trillian-opensource-ci/log_server@sha256:f3ba85189d599d2752e57e71b641100e711683b9b8e1d4f17769e047a2864cea
    command:
    - --mysql_uri=test:zaphod@tcp(db:3306)/test
    - --rpc_endpoint=:50051
    - --http_endpoint=:8080
    - --alsologtostderr
    expose:
    - "8080"  # HTTP includes prometheus metrics
    - "50051" # gRPC
    ports:
    - "54051:50051" # Expose gRPC Endpoint to host to permit log creation externally

  trillian-log-signer:
    depends_on:
    - db
    # See https://console.cloud.google.com/gcr/images/trillian-opensource-ci/GLOBAL
    image: gcr.io/trillian-opensource-ci/log_signer@sha256:d17bdcce6c6adf602ad57aa15d18ea4a72259a86b2017a2377442bd972b594d9
    command:
    - --mysql_uri=test:zaphod@tcp(db:3306)/test
    - --rpc_endpoint=:50051
    - --http_endpoint=:8080
    - --batch_size=1000
    - --sequencer_guard_window=0
    - --sequencer_interval=200ms
    - --force_master
    - --logtostderr
    expose:
    - "8080"  # HTTP includes prometheus metrics
    - "50051" # gRPC

volumes:
  trillian-data:
    external: true
